version: '3.3'
services: 
  rancher:
    image: rancher/rancher
    container_name: rancher
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes: 
      - /opt/docker/rancher/rancher:/var/lib/rancher
      - /opt/docker/rancher/rancher:/var/log/auditlog
