version: '3.3'

services:
  emqx:
    image: jphuc96/emqx:latest
    restart: always
    ports:
      - 1883:1883 #TCP 
      - 8082:8083 #WS
      - 18083:18083 #UI
      - 9091:9091 #prometheus
    volumes: 
      - emqx:/opt/emqx/
    #   - /opt/docker/emqx/data:/opt/emqx/data
    #   - /opt/docker/emqx/etc:/opt/emqx/etc
    #   - /opt/docker/emqx/log:/opt/emqx/log

volumes: 
  emqx: