version: "3.1"
services:
  pydio:
    image: linuxserver/pydio
    container_name: pydio
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /opt/docker/pydio/config:/config
      - /opt/docker/pydio/data:/data
    ports:
      - 10443:443
    restart: unless-stopped