version: '3.1'
services: 
  cloudflare-ddns:
    image: joshuaavalon/cloudflare-ddns
    container_name: cloudflare-ddns
    restart: always
    environment: 
      - ZONE=sudojoss.com
      - HOST=ops.sudojoss.com
      - EMAIL=${CLOUDFLARE_EMAIL}
      - API=${CLOUDFLARE_API_KEY}
      - TTL=1
      - PROXY=false
      