version: '3.1'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - redmine
    environment:
      MYSQL_ROOT_PASSWORD: mysql_rootpasswd
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine

  redmine:
    image: redmine:3.4.6-passenger
    restart: always
    networks:
      - redmine
    volumes:
      - redmine-data:/usr/src/redmine/files
    ports:
      - 3001:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
    depends_on: 
      - mysql

volumes:
  mysql-data:
  redmine-data:

networks:
  redmine:
    driver: bridge