version: '3.1'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - traefik_proxy
    environment:
      MYSQL_ROOT_PASSWORD: mysql_rootpasswd
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine
    labels:
      - traefik.enable=false

  redmine:
    image: redmine:3.4.6-passenger
    restart: always
    networks:
      - traefik_proxy
    volumes:
      - redmine-files:/usr/src/redmine/files/
      - redmine-plugins:/usr/src/redmine/plugins/
      - redmine-themes:/usr/src/redmine/public/themes/
    ports:
      - 127.0.0.1:3000:3000
    environment:
      REDMINE_DB_MYSQL: mysql
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_DB_DATABASE: redmine
    depends_on: 
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.backend=redmine"
      - "traefik.entrypoints=https"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:redmine.sudojoss.com"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=3000"

volumes:
  mysql-data:
  redmine-files:
  redmine-plugins:
  redmine-themes:

networks:
  traefik_proxy:
    external: true