version: "3.3"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: unless-stopped
    networks:
      - nginx-proxy
      - internal
    volumes:
      - /opt/docker/gitea/data:/data
    ports:
      - 60000:3000
      - 222:22
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: gitea-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    networks:
      - internal
    volumes:
      - /opt/docker/gitea/mysql:/var/lib/mysql

networks: 
  nginx-proxy:
    external: true
  internal:
    driver: bridge