# docker run -d \
#     --name=handbrake \
#     -p 5800:5800 \
#     -v /docker/appdata/handbrake:/config:rw \
#     -v $HOME:/storage:ro \
#     -v $HOME/HandBrake/watch:/watch:rw \
#     -v $HOME/HandBrake/output:/output:rw \
#     jlesage/handbrake

version: '3.1'
services: 
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    restart: unless-stopped
    ports: 
      - 5800:5800
    environment: 
      - USER_ID=1000
      - GROUP_ID=1000
    volumes: 
      - /opt/docker/handbrake/config:/config:rw
      - /opt/docker/handbrake/watch:/watch:rw
      - /opt/docker/handbrake/output:/output:rw
      - /home/jphuc96:/storage:ro