version: '3.3'

services:
  ubuntu:
    image: ubuntu:18.04
    restart: always
    command:
      - /bin/bash
    networks: 
      - ubuntu
    ports:
      - "10022:22"
    volumes:
      - "/home/jphuc96/docker_data/ubuntu/home:/home"

networks:
  ubuntu:
    driver: bridge