version: '3.3'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "472"
    # environment: 
    #   - "GF_SERVER_ROOT_URL=http://localhost:3000/grafana/"
    networks: 
      - nginx-proxy
    ports: 
      - 3000:3000
    volumes: 
      - /opt/docker/grafana/config:/etc/grafana
      - /opt/docker/grafana/data:/var/lib/grafana

networks: 
  nginx-proxy:
    external: true