version: '3.1'

services:
  nextcloud:
      restart: always
      image: linuxserver/nextcloud
      container_name: nextcloud
      volumes:
        - /opt/docker/nextcloud/config:/config
        - /opt/docker/nextcloud/data:/data
        - /home/jphuc96:/ext-data/home/jphuc96
        - /opt:/ext-data/opt
        - /etc:/ext-data/etc
      environment:
        - PUID=1000
        - PGID=1000
        - MYSQL_HOST=nextcloud-db
        - MYSQL_PASSWORD=nextcloud
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
      depends_on:
        - db
      networks:
        - nginx-proxy
        - internal
      ports:
        - 10443:443
  db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - internal
    volumes:
      - /opt/docker/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_rootpasswd
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

networks:
  nginx-proxy:
    external: true
  internal:
    driver: bridge
