version: '3.3'

services:
  openhab:
    image: "openhab/openhab:2.4.0"
    restart: always
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/opt/docker/openhab/openhab_addons:/openhab/addons"
      - "/opt/docker/openhab/openhab_conf:/openhab/conf"
      - "/opt/docker/openhab/openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Asia/Ho_Chi_Minh"
      USER_ID: 1000
      GROUP_ID: 1000