# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:4.1.6
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpasswd
    volumes: 
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb

volumes: 
  mongo-db:
  mongo-configdb: