version: '3.1'
services:
  nginx:
    image: linuxserver/nginx
    container_name: nginx
    restart: unless-stopped
    networks: 
      - nginx-proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /opt/docker/nginx:/config
    ports:
      - 80:80
      - 443:443
      # - 27017:27017
      # - 3306:3306
    # mem_limit: 4096m

networks: 
  nginx-proxy:
    external: true
