version: '3.3'
services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    user: 1000:1000
    restart: unless-stopped
    networks: 
      - nginx-proxy
    ports:
      - 8080:8080
      - 50000:50000
    volumes: 
      - /opt/docker/jenkins:/var/jenkins_home

networks: 
  nginx-proxy:
    external: true