version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    networks: 
      - nginx-proxy
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql_rootpasswd
    volumes: 
      - /opt/docker/mysql/data:/var/lib/mysql
      - /opt/docker/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf


networks: 
  nginx-proxy:
    external: true