version: '3'
services:

  ghost:
    image: ghost:2.7.1
    restart: always
    networks:
      - traefik_proxy
    ports:
      - 127.0.0.1:2368:2368
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ghost"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:blog.sudojoss.com"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.port=2368"
    environment:
      url: http://blog.sudojoss.com
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: mysql_rootpasswd
      database__connection__database: ghost
    volumes:
      - ghost-content:/var/lib/ghost/content
      - /home/jphuc96/docker_data/ghost/config.production.json:/var/lib/ghost/config.production.json
  db:
    image: mysql:5.7
    restart: always
    networks:
      - traefik_proxy
    environment:
      MYSQL_ROOT_PASSWORD: mysql_rootpasswd
    labels:
      - "traefik.enable=false"
    volumes:
      - ghost-mysql:/var/lib/mysql

volumes:
  ghost-content:
  ghost-mysql:

networks:
  traefik_proxy:
    external: true