version: '3.3'

services:

  nextcloud:
      restart: always
      image: linuxserver/nextcloud
      volumes:
        - nextcloud-config:/config
        - nextcloud-data:/data
      environment:
        - PUID=1000
        - PGID=1000
        - MYSQL_HOST=db
        - MYSQL_PASSWORD=nextcloud
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
      depends_on:
        - db
      networks:
        - traefik_proxy
        - nextcloud
      labels:
        - "traefik.enable=true"
        - "traefik.protocol=https"
        - "traefik.port=443"
        - "traefik.backend=nextcloud"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:nextcloud.sudojoss.com"
        - "traefik.docker.network=traefik_proxy"
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nextcloud
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_rootpasswd
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

volumes:
  db:
  nextcloud-data:
  nextcloud-config:

networks:
  traefik_proxy:
    external: true
  nextcloud:
    driver: bridge