version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    networks: 
      - nginx-proxy
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_rootpasswd
    volumes: 
      - /opt/docker/mongo/db:/data/db
      - /opt/docker/mongo/configdb:/data/configdb

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: unless-stopped
  #   networks: 
  #     - nginx-proxy
  #   # ports:
  #   #   - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_rootpasswd

networks: 
  nginx-proxy:
    external: true